library(lattice)
prDat <- read.table("GSE4051_data.tsv")
str(prDat, max.level = 0)
prDes <- readRDS("GSE4051_design.rds")
str(prDes)
set.seed(987)
(theGene <- sample(1:nrow(prDat), 1))
pDat <- data.frame(prDes, gExp = unlist(prDat[theGene, ]))
str(pDat)
aggregate(gExp ~ gType, pDat, FUN = mean)
stripplot(gType ~ gExp, pDat)
ttRes <- t.test(gExp ~ gType, pDat)
str(ttRes)
ttRes$statistic
ttRes$p.value
(theGene2 <- sample(1:nrow(prDat), 1))
pDat2 <- data.frame(prDes, gExp = unlist(prDat[theGene2, ]))
aggregate(gExp ~ gType, pDat2, FUN = mean)
stripplot(gType ~ gExp, pDat2)
ttRes2 <- t.test(gExp ~ gType, pDat2, var.equal=FALSE)
ttRes2cv <- t.test(gExp ~ gType, pDat2, var.equal=TRUE)
wRes <- wilcox.test(gExp ~ gType, pDat2)
ksRes <- ks.test(pDat2$gType, pDat2$gExp)
data.frame("method"=c(ttRes2$method, ttRes2cv$method, wRes$method, ksRes$method), 
           p.value=c(ttRes2$p.value, ttRes2cv$p.value, wRes$p.value, ksRes$p.value))